export const LINKS = [
  { id: 'id-fw', group: 'boundaryLinks', from: 'identity', fromPort: 'right', to: 'firewall', toPort: 'left', cls: 'gray', marker: 'arrow-gray' },
  { id: 'gateway-jump', group: 'boundaryLinks', from: 'itGateway', fromPort: 'right', to: 'jump', toPort: 'left', cls: 'gray', marker: 'arrow-gray' },
  { id: 'fw-core', group: 'boundaryLinks', from: 'firewall', fromPort: 'right', to: 'core', toPort: 'left', cls: 'gray', marker: 'arrow-gray' },
  { id: 'broker-soc', group: 'boundaryLinks', from: 'broker', fromPort: 'left', to: 'ticketing', toPort: 'bottom', cls: 'blue', marker: 'arrow-blue', route: 'enterprise-return' },
  { id: 'core-historian', group: 'opsLinks', from: 'core', fromPort: 'right', to: 'historian', toPort: 'left', cls: 'service', route: 'ops-up', label: 'OPC-UA / historian reads' },
  { id: 'core-engineering', group: 'opsLinks', from: 'core', fromPort: 'right', to: 'engineering', toPort: 'left', cls: 'service', route: 'ops-down', label: 'engineering access' },
  { id: 'core-services', group: 'opsLinks', from: 'core', fromPort: 'right', to: 'services', toPort: 'left', cls: 'service', route: 'ops-services-direct' },
  { id: 'core-dist', group: 'controlLinks', from: 'core', fromPort: 'bottom', to: 'dist', toPort: 'top', cls: 'backbone', label: 'trunk' },
  { id: 'dist-scada', group: 'controlLinks', from: 'dist', fromPort: 'right', to: 'scada', toPort: 'left', cls: 'service', route: 'control-up' },
  { id: 'dist-hmi', group: 'controlLinks', from: 'dist', fromPort: 'bottom', to: 'hmi', toPort: 'bottom', cls: 'service', route: 'control-bus' },
  { id: 'dist-mirror', group: 'controlLinks', from: 'dist', fromPort: 'bottom', to: 'mirror', toPort: 'left', cls: 'service', route: 'control-mirror' },
  { id: 'markvie-scada', group: 'fieldLinks', from: 'markvie', fromPort: 'top', to: 'scada', toPort: 'bottom', cls: 'protocol', route: 'field-bus', label: 'SRTP / EGD' },
  { id: 'clx-hmi', group: 'fieldLinks', from: 'controllogix', fromPort: 'top', to: 'hmi', toPort: 'bottom', cls: 'protocol', route: 'field-bus', label: 'EtherNet/IP' },
  { id: 'rtu-mirror', group: 'fieldLinks', from: 'rtu', fromPort: 'top', to: 'mirror', toPort: 'bottom', cls: 'protocol', route: 'field-bus' },
  { id: 's7-dist', group: 'fieldLinks', from: 's7', fromPort: 'top', to: 'dist', toPort: 'bottom', cls: 'protocol', route: 'field-low-bus', label: 'S7comm' },
  { id: 'span-boundary', group: 'sensorLinks', from: 'firewall', fromPort: 'bottom', to: 'sensorBoundary', toPort: 'top', cls: 'orange', marker: 'arrow-orange', route: 'boundary-span', label: 'SPAN only' },
  { id: 'span-control', group: 'sensorLinks', from: 'dist', fromPort: 'left', to: 'sensorControl', toPort: 'right', cls: 'orange', marker: 'arrow-orange', route: 'control-span' },
  { id: 'sensor-boundary-store', group: 'storeLinks', from: 'sensorBoundary', fromPort: 'bottom', to: 'siteStore', toPort: 'left', cls: 'orange', marker: 'arrow-orange', route: 'sensor-store-west' },
  { id: 'sensor-control-store', group: 'storeLinks', from: 'sensorControl', fromPort: 'bottom', to: 'siteStore', toPort: 'top', cls: 'orange', marker: 'arrow-orange', route: 'sensor-store-direct' },
  { id: 'site-central', group: 'storeLinks', from: 'siteStore', fromPort: 'left', to: 'centralStore', toPort: 'right', cls: 'blue', marker: 'arrow-blue', label: 'metadata + detections' },
  { id: 'central-soc', group: 'storeLinks', from: 'centralStore', fromPort: 'left', to: 'soc', toPort: 'left', cls: 'blue', marker: 'arrow-blue', route: 'soc-handoff' }
];
