export const NODES = [
  { id: 'soc', kind: 'siem', label: 'SOC / SIEM', sub: 'Splunk / workflow' },
  { id: 'identity', kind: 'identity', label: 'AD / DNS', sub: 'identity services' },
  { id: 'ticketing', kind: 'app', label: 'Tickets', sub: 'case handoff' },
  { id: 'itGateway', kind: 'gateway', label: 'IT Gateway', sub: 'approved route' },
  { id: 'firewall', kind: 'firewall', label: 'Boundary Firewall', sub: 'allow-listed flows', variant: 'boundary' },
  { id: 'jump', kind: 'workstation', label: 'Jump Host', sub: 'MFA + session logs', variant: 'boundary' },
  { id: 'broker', kind: 'server', label: 'DMZ Broker', sub: 'egress proxy', variant: 'boundary' },
  { id: 'core', kind: 'switch', label: 'OT Core Switch', variant: 'switch' },
  { id: 'historian', kind: 'database', label: 'Historian', sub: 'PI / OPC-UA' },
  { id: 'engineering', kind: 'workstation', label: 'Engineering WS', sub: 'PLC tools' },
  { id: 'services', kind: 'server', label: 'Patch / NTP', sub: 'OT services' },
  { id: 'dist', kind: 'switch', label: 'Control Dist Switch', variant: 'switch' },
  { id: 'scada', kind: 'server', label: 'SCADA Server', sub: 'operator control' },
  { id: 'hmi', kind: 'workstation', label: 'HMI Pair', sub: 'view / alarm' },
  { id: 'mirror', kind: 'database', label: 'Local Mirror', sub: 'history cache' },
  { id: 'markvie', kind: 'controller', label: 'GE Mark VIe', sub: 'SRTP / EGD', variant: 'controller' },
  { id: 'controllogix', kind: 'controller', label: 'ControlLogix', sub: 'EtherNet/IP', variant: 'controller' },
  { id: 'rtu', kind: 'rtu', label: 'SEL RTU', sub: 'DNP3', variant: 'controller' },
  { id: 's7', kind: 'controller', label: 'S7-400', sub: 'S7comm', variant: 'controller' },
  { id: 'sensorBoundary', kind: 'sensor', label: 'Dragos Sensor', sub: 'boundary SPAN', variant: 'dragos' },
  { id: 'sensorControl', kind: 'sensor', label: 'Dragos Sensor', sub: 'control trunk', variant: 'dragos' },
  { id: 'siteStore', kind: 'analytics', label: 'SiteStore', sub: 'local analysis', variant: 'dragos' },
  { id: 'centralStore', kind: 'analytics', label: 'CentralStore', sub: 'multi-site view', variant: 'dark' }
];
