export const STEPS = [
  { label: 'Orient', groups: ['enterprise', 'boundary', 'operations'], links: [], narration: '<span class="tag">TALK</span>"I start with the customer network: enterprise services, the authorization boundary, and the OT operations enclave. We are not drawing Purdue levels. We are drawing where traffic actually has to cross."' },
  { label: 'Boundary', groups: ['enterprise', 'boundary', 'operations'], links: ['boundaryLinks'], narration: '<span class="tag point">POINT</span>"Next I mark the boundary paths: identity and approved gateway flows into the boundary controls, then the allowed plant-side path. This is where I ask what is approved, logged, and blocked."' },
  { label: 'Boundary Focus', groups: ['enterprise', 'boundary', 'operations'], links: ['boundaryLinks'], focus: ['boundary', 'boundaryLinks'], narration: '<span class="tag point">FOCUS</span>"When the drawing gets busy, I fade the context back and isolate the boundary decision: what is permitted, what is monitored, and who owns the exception."' },
  { label: 'Ops Services', groups: ['enterprise', 'boundary', 'operations'], links: ['boundaryLinks', 'opsLinks'], narration: '<span class="tag draw">DRAW</span>"Then I add the services operators actually depend on: core switching, historian, engineering workstation, patch and time sources. Every service link is docked to a device edge."' },
  { label: 'Control', groups: ['enterprise', 'boundary', 'operations', 'control'], links: ['boundaryLinks', 'opsLinks'], narration: '<span class="tag draw">DRAW</span>"Now the control network appears as its own enclave. Boxes come before wires so the customer never sees orphan line clusters."' },
  { label: 'Trunks', groups: ['enterprise', 'boundary', 'operations', 'control'], links: ['boundaryLinks', 'opsLinks', 'controlLinks'], narration: '<span class="tag draw">DRAW</span>"The trunk and control service flows are routed through reserved lanes. If a route crosses a box, the validation layer catches it."' },
  { label: 'Field', groups: ['enterprise', 'boundary', 'operations', 'control', 'field'], links: ['boundaryLinks', 'opsLinks', 'controlLinks'], narration: '<span class="tag draw">DRAW</span>"Now I add vendor-specific controller families and protocols. This gives the whiteboard real OT signal instead of abstract layers."' },
  { label: 'Protocols', groups: ['enterprise', 'boundary', 'operations', 'control', 'field'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks'], narration: '<span class="tag draw">DRAW</span>"Only after the endpoint boxes exist do protocol paths appear. These are the conversations we want to baseline and detect against."' },
  { label: 'Protocol Focus', groups: ['enterprise', 'boundary', 'operations', 'control', 'field'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks'], focus: ['control', 'field', 'fieldLinks'], narration: '<span class="tag point">FOCUS</span>"Now I quiet the enterprise and boundary context so the customer can read the actual OT protocol conversations without losing where they sit."' },
  { label: 'Gap', groups: ['enterprise', 'boundary', 'operations', 'control', 'field', 'gap'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks'], narration: '<span class="tag point">POINT</span>"Here is the customer pain: access logs and tickets do not prove what controller traffic crossed the wire or whether it matched normal process behavior."' },
  { label: 'Sensors', groups: ['enterprise', 'boundary', 'operations', 'control', 'field', 'gap', 'monitoring'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks'], narration: '<span class="tag draw">DRAW</span>"Then I place passive sensors. No inline dependency, no active scan requirement, and no pretend magic box in the middle of the plant."' },
  { label: 'SPANs', groups: ['enterprise', 'boundary', 'operations', 'control', 'field', 'gap', 'monitoring'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks', 'sensorLinks'], narration: '<span class="tag draw">DRAW</span>"The sensors attach to specific observation points: boundary SPAN and control trunk SPAN. The link appears only when both endpoint devices are visible."' },
  { label: 'Sensor Focus', groups: ['enterprise', 'boundary', 'operations', 'control', 'field', 'gap', 'monitoring'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks', 'sensorLinks'], focus: ['monitoring', 'sensorLinks'], narration: '<span class="tag point">FOCUS</span>"Then I fade the plant context and highlight the passive collection architecture: where the sensor listens and what it forwards."' },
  { label: 'Handoff', groups: ['enterprise', 'boundary', 'operations', 'control', 'field', 'monitoring'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks', 'sensorLinks', 'storeLinks'], narration: '<span class="tag draw">DRAW</span>"Finally, SiteStore and CentralStore carry metadata and detections northbound into the SOC process. Raw packet capture stays governed by the plant plan."' },
  { label: 'Close', groups: ['enterprise', 'boundary', 'operations', 'control', 'field', 'monitoring', 'close'], links: ['boundaryLinks', 'opsLinks', 'controlLinks', 'fieldLinks', 'sensorLinks', 'storeLinks'], narration: '<span class="tag ask">ASK</span>"The close is practical: confirm ports, SPAN source, baseline window, SOC handoff, and the proof-of-value criteria for the Dragos demo."' }
];
